version: '3.9'

services:
  note.service:
    image: ${DOCKER_REGISTRY-}notesappbackendservicesnoteapi
    container_name: note.service
    build:
      context: .
      dockerfile: backend/src/Services/Note/NotesApp.Backend.Services.Note.Api/Dockerfile
    networks:
      - backend-data
      - frontend-backend
    depends_on:
      - mongodb-primary
    environment:
      - ConnectionStrings__MongoStore=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOSTNAME}:${MONGODB_PORT}

  mongodb-primary:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-data
    expose:
      - 27017

networks:
  backend-data:
  frontend-backend:

volumes:
  mongo_data:
