import "bootstrap/dist/css/bootstrap.css";
import "./globals.scss";
import BootstrapClient from "@/components/bootstrap-client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // TODO: Switch data-bs-theme value to auto when implementing theme toggle feature
    <html lang="en" data-bs-theme="dark">
      <body>
        {children}
        <BootstrapClient/>
      </body>
    </html>
  );
}
